In [4]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn import metrics, datasets
from sklearn.linear_model import LogisticRegression
import matplotlib.patches as mpatches
from sklearn.metrics import confusion_matrix, accuracy_score


In [5]:
data = pd.read_csv("data/austin_weather.csv")


In [9]:
cle_data = data.drop(['Events','Date','SeaLevelPressureHighInches','SeaLevelPressureLowInches'], axis = 1)

cle_data['PrecipitationSumInches'].replace('T','0.001', inplace=True)
print(cle_data.shape)

(1319, 17)


In [12]:
cle_data.drop(cle_data.index[cle_data['TempHighF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['TempAvgF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['TempLowF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['DewPointHighF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['DewPointAvgF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['DewPointLowF'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['HumidityHighPercent'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['HumidityAvgPercent'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['HumidityLowPercent'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['VisibilityHighMiles'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['VisibilityAvgMiles'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['VisibilityLowMiles'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['WindHighMPH'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['WindAvgMPH'] == '-'], inplace = True)
cle_data.drop(cle_data.index[cle_data['WindGustMPH'] == '-'], inplace = True)

In [14]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(cle_data)

      TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF DewPointLowF  \
0            74        60        45            67           49           43   
1            56        48        39            43           36           28   
2            58        45        32            31           27           23   
3            61        46        31            36           28           21   
4            58        50        41            44           40           36   
5            57        48        39            39           36           33   
6            60        53        45            41           39           37   
7            62        51        40            43           39           33   
8            64        50        36            49           41           28   
9            44        40        35            31           26           21   
10           55        46        36            31           28           23   
11           69        54        39            51   

In [15]:
cle_data.shape

(1305, 17)

will add some thing here

X_train: (923, 16)
y_train: (923,)
X_test: (396, 16)
y_train: (396,)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

will be addig something here as well

Test accuracy: 0.6590909090909091
[[257   3   1 ...   0   0   0]
 [ 28   4   0 ...   0   0   0]
 [  8   5   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


updating of comments is very important

Train accuracy:   0.7388949079089924


train accuracy is brilliant

NameError: name 'days' is not defined